"""update

Revision ID: 066964ea7f6d
Revises: a905b069e1e1
Create Date: 2024-05-14 18:36:04.599276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066964ea7f6d'
down_revision = 'a905b069e1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.drop_column('selflike_num')
        batch_op.drop_column('like_num')
        batch_op.drop_column('selfcomment_num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selfcomment_num', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('like_num', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('selflike_num', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
