"""update

Revision ID: 6cc8fd9a8657
Revises: 066964ea7f6d
Create Date: 2024-05-14 20:37:31.145250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc8fd9a8657'
down_revision = '066964ea7f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.drop_column('post_num')
        batch_op.drop_column('badges')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badges', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('post_num', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
