"""update

Revision ID: a22f6cf80d9e
Revises: 4579aad4d02d
Create Date: 2024-05-14 22:04:54.300195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22f6cf80d9e'
down_revision = '4579aad4d02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_num', sa.INTEGER(), nullable=True, comment='comment numbers'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_post', schema=None) as batch_op:
        batch_op.drop_column('comment_num')

    # ### end Alembic commands ###
