"""add user's post_num.

Revision ID: 3a1e1459b979
Revises: b2ea294b35eb
Create Date: 2024-05-12 15:40:55.580085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1e1459b979'
down_revision = 'b2ea294b35eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_num', sa.INTEGER(), nullable=True, comment='Number of posts made by the user'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.drop_column('post_num')

    # ### end Alembic commands ###
