"""update

Revision ID: 4579aad4d02d
Revises: 6cc8fd9a8657
Create Date: 2024-05-14 21:59:07.539028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4579aad4d02d'
down_revision = '6cc8fd9a8657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_post', schema=None) as batch_op:
        batch_op.drop_column('comment_num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_num', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
