"""fix comment count func

Revision ID: 79064a8b26aa
Revises: a905b069e1e1
Create Date: 2024-05-14 17:47:24.440550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79064a8b26aa'
down_revision = 'a905b069e1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('replied_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replied_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 't_comments', ['replied_id'], ['id'])

    # ### end Alembic commands ###
