"""add t_like update

Revision ID: cf93fa6757fa
Revises: e1ca64e587d5
Create Date: 2024-05-13 20:34:16.222371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf93fa6757fa'
down_revision = 'e1ca64e587d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('l_user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('l_post_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 't_user', ['l_user_id'], ['id'])
        batch_op.create_foreign_key(None, 't_post', ['l_post_id'], ['id'])
        batch_op.drop_column('post_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 't_post', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 't_user', ['user_id'], ['id'])
        batch_op.drop_column('l_post_id')
        batch_op.drop_column('l_user_id')

    # ### end Alembic commands ###
