"""Add some

Revision ID: ddbfc16e8b57
Revises: 9754a1ec8c52
Create Date: 2024-05-12 16:34:26.435559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbfc16e8b57'
down_revision = '9754a1ec8c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selfcomment_num', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.drop_column('selfcomment_num')

    # ### end Alembic commands ###
